/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    tutorialSlidebar: [{
        type: 'category',
        label: 'Tutorial',
        items: [
            'intro',
            {
                type: 'autogenerated',
                dirName: 'tutorial', // Generate sidebar slice from docs/tutorials/easy
            }
        ],
    }],
    kivalaSidebar: [{
        type: 'category',
        label: 'Kivala',
        items: [
            'kivala',
            {
                type: 'autogenerated',
                dirName: 'kivala', // Generate sidebar slice from docs/tutorials/easy
            }
        ],
    }],
    angularSidebar: [{
        type: 'category',
        label: 'Angular',
        items: [
            'angular',
            {
                type: 'autogenerated',
                dirName: 'angular', // Generate sidebar slice from docs/tutorials/easy
            }
        ],
    }],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
     */
};

module.exports = sidebars;